### ISSUE TITLE
Vertical alignment inconsistencies inside and outside ControlGroup

### ISSUE THREAD

**Issue by angrytongan** [vrimar/construct-ui#13]
There appears to be some slight vertical alignment inconsistencies between elements, both inside and outside of a ControlGroup, with and without icons.

* A Button, Input and Select will be aligned with the bottom of the Select. The Select takes one pixel more than the Button and Input.
* A Button, Input and Select in a ControlGroup will all align on a single bottom, with one pixel row free above all elements.
* An Input, Button and Select in a ControlGroup will all align on a single bottom, with one pixel row free above all elements.
* A Button with an iconLeft but no label, Input and Select will have the input pushed two pixels down from the top of the Button. The Select will be pushed down one pixel from the top of the Button.
* A Button with an iconLeft but no label, Input and Select in a ControlGroup will align all elements at the top, leaving two pixels below the input and one below the Button and Select.
* An Input, Button with an iconLeft but no label and Select will align all elements at the bottom, leaving two pixels above the elements.

It looks like a Button with / without an iconLeft / label changes the vertical size of the button and it's vertical position. Additionally, the first element in a ControlGroup looks like it "aligns" following elements.

```javascript
const {
    Button,
    ControlGroup,
    FocusManager,
    Icon,
    Input,
    Select,

} = CUI;

const ControlGroupAlignment = () => {
    return {
        view: () => {
            return [
                /*
                 * Buttons: labels only.
                 */
                m('', {
                    style: 'margin: 1em; background: #000;',
                }, [
                    m(Button, { label: 'a' }),
                    m(Input, { placeholder: 'no controlgroup' }),
                    m(Select, { options: [ 'b', 'c' ] }),

                    m(ControlGroup, [
                        m(Button, { label: 'a' }),
                        m(Input, { placeholder: 'in controlgroup' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),

                    m(ControlGroup, [
                        m(Input, { placeholder: 'first in controlgroup' }),
                        m(Button, { label: 'a' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),
                ]),

                /*
                 * Buttons: icons only.
                 */
                m('', {
                    style: 'margin: 1em; background: #000;',
                }, [
                    m(Button, { iconLeft: 'settings' }),
                    m(Input, { placeholder: 'no controlgroup' }),
                    m(Select, { options: [ 'b', 'c' ] }),

                    m(ControlGroup, [
                        m(Button, { iconLeft: 'settings' }),
                        m(Input, { placeholder: 'in controlgroup' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),

                    m(ControlGroup, [
                        m(Input, { placeholder: 'first in controlgroup' }),
                        m(Button, { iconLeft: 'settings' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),
                ]),

                /*
                 * Buttons: icons and labels only.
                 */
                m('', {
                    style: 'margin: 1em; background: #000;',
                }, [
                    m(Button, { label: 'a', iconLeft: 'settings' }),
                    m(Input, { placeholder: 'no controlgroup' }),
                    m(Select, { options: [ 'b', 'c' ] }),

                    m(ControlGroup, [
                        m(Button, { label: 'a', iconLeft: 'settings' }),
                        m(Input, { placeholder: 'in controlgroup' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),

                    m(ControlGroup, [
                        m(Input, { placeholder: 'first in controlgroup' }),
                        m(Button, { label: 'a', iconLeft: 'settings' }),
                        m(Select, { options: [ 'b', 'c' ] }),
                    ]),
                ]),

                /*
                 * Buttons with / without labels and icons.
                 */
                m('', {
                    style: 'margin: 1em; background: #000;',
                }, [
                    m(Button, { label: 'a' }),
                    m(Button, { iconLeft: 'settings' }),

                    m(ControlGroup, [
                        m(Button, { label: 'a' }),
                        m(Button, { iconLeft: 'settings' }),
                    ]),

                    m(ControlGroup, [
                        m(Button, { iconLeft: 'settings' }),
                        m(Button, { label: 'a' }),
                    ]),
                ]),
            ];
        },
    };
};

document.addEventListener('DOMContentLoaded', () => {
    m.route(document.body, '/', {
        '/': ControlGroupAlignment
    });
});
```

**Comment by vrimar** [comment]
Thanks for the detailed report, I really appreciate it. 

I've committed a fix but I'll have to test other browsers before I can publish a new version.

Here's an updated [flems](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIAW94AcyoHoCBXAOxwGsBzAOlgHsBbAh0seAJ2IQFpiBLAAIAGGgEZxwglH4AjAv1JIIADzpgwIADQgAZvxibUAbVCkAhowhoQNLIyjaQrRKXg2QAXy1nL19DQAVpo6LhBuNqzsAATAADqk0UnRAELE2PSkWgnJ0QDCmZz0UADiHPTEONmJyQBi9LDEYACy5hZUEBzVuQCSrN3JPeTpA0kAytBw8NUJntEAvPkAqj0A3AkJUfD5heWl5ZUAgjJUpFZuC9EAFACUCwB8sTnJHBDwxByJ8TW5SQBu-AgAHdUNc7vNHt9ftDoq93p9osZnjCYQQAFTIlHQtGpdLwTL4aJQcyyaBgaKZKAATxomKxuTRBDp9OijCuAHJ2Vonj8WdD2FSYKD2YxzBwqIpQWIIIxVtFZOZYNQDkpQQBiYSa1Zc5n07yI3V81lXNIZLKxIkk6DC8zs6KeG6jI25NlDHAjC04YmwCAYYrKDjC0j0aIuPZUA44O0Op3OpJsiYwBDc4AUnDwfgE0HGaLs2Rc3OwO0AXXtjo2vLjxoKbj2ZQqVQNlaryTZpvx5tTxNJUBt0fLzZbxrdHtTXsVvv9nWFilDu2KEYb-djQ+NiamKbTGaziNz+e57KL0VLMcNfOLA7PLLZNaK+wb3KRg5bruG0093snUADwv0HBis5hgukbLlezptnimSbt21q5raZYrkOCaTMmFr0OmmZsNme4FoeJYIWBWIXohRGXs+KLooRvw4u2O78FEFKkNStLkSijJUa2HIFlCq4CkKuaiuKkrRNKsryoqyoVKq0QalqOqsdC+pPquxq0Z20T0ZkAAyEC6PAwqQNgihUGAoEKVir7uu+Y6fn637TrmwZzrWwFLgR5koshSbWVumGEjmea4UeJ5kSpN7zvelSPhx9IQWam6aaQOl6QZbwZqQJlmSpLpXCOPnjj6dk-rmgERYulRZdl8ZXOuqGpuh25YbugUHsF7kqcRFZhVct51pG0UedeuVvpuBVfsV7J-gBiRAVA5VRu1VWqZB6mJcl+m5oZ6WZYtVVeRuaEYTuAX7oW+GnoN0KdZdx6hXGlE3dENErYSiXkm0SCWj25KUjSMVJOxN1spyKb-bkfEQMKgkSqQUoynKCpKuV0mycI2okSiSlg5xanQVavZwQWa26Rt7JbcZpm7S+w1WaNtlToGjkhrN82VUhNUoT5DV+dhLVnce7nY9VvXFPWUVNkty3xRaMEE+ytrcsTKWbWlFNs9llmjtEY1FQ57KlS5c0gVT3W1VzR1NSdQXnQOHV3ezIuRY2ylLZr+X0-ZjOTfw-7bAbd6sybq5xR2eM9n2iusOtqVGRllMXZL+11b5x04a1NsYyy11Vtd-0PS2z1muSQL8PAGDRAQ0Ql2XFTbLL71KBpUQsQXTJA1xoOPckENQ2KMNw2JiOSWQSDqpqaPyVWWNd9VuMy-jfZB+BJorQlUckzH23x-b1OO2LztC78IdQfP4eE0v1Nz6mSuk+TcfqznO9VuFhv7wNicr9L1-r8rZOq-fF9n6f1DqfWC8sH5xmzpA22Wd1jPm8JiTwcCkEVkYDQRgUl4BXCQA0Yg5x4A0FkPQJAVJuR70jMcfgpx8E3CcJAbyfkbBiGEAAdlQAAFnYV4HwIALBWBsOoEIzhCjhHcOgLwxYdAyFIBQIwpheF+BsIwUuGAOAGCcB8Rw6AsC4HwEQMglBaAMGYMosuaioCCAkBIAAbAQUxqiDBBCEfAKkOB-DgFgGo9M3DfD8PQFsLgvABDoMUE4jRHAtGYGwHgQgJByDUDoEwFgBJODcHgHwIQogrFSBkPIAJaSMkhNIGEnQLi3E2DAJ4-g3jvC+PcYoZQahYAaHCZEnRMT9HxKMUk-JQTMniEkNIOQCglCqEEU4Mp7iIZOBwOYeAsAMAQDkcYYwwgpHmCpKgRQ0iIA8F0DAFQqwQCSOMGIHQfxOgZlgOYKAPAblUNhsopASAYBHJOWsvQByeBIB9lMTCqAODHK0AAZgAExaAAKzsK0Cw0F7DwWwvhSc1ZOhUDBiwXQAQPAFRgHorQk5Zy0DoquJi-gPBa47KQPirQKKQDRFJTwMAOBFCkGnOYXQQKwWQrOWICFmoACcWheUCuRR8tF9AMWNDJTivFQLTmouJQyilihkDUtpfSqVjLmWkFZYGdlnLwUQp5XygAHCaoVpqTWioVRKklmqZWwDVYS8VkqsXKtZVSuVHyNVYqZSytlHLJFcqNRasQ1jrGhvDdakA0rzC4sdXK51irNXutVV6nQPqyVMqBWGkFEKLWgoheC3lhbQXRq2UxFVeyDmJp0KsC5HArk3LuScR5-BnkwHTV4BlsgVpArhVodhEbQUmrECa-NI6x0Qujdsqt+zVBvJpYShtTbbn3NOKgJ5LyICLtpdDRQPA1FUCwP26FQ683WOBSwi9V6Z08Fmjwea0Ra22E1Y0dgTBGWc3lKvBlD6n1doZYoKyGk3wGphde4F1jhBiDOVBmDYho3Ek2bO1l1aF0vpXfRZt6620dp3V23DPBS4ynwD6CIQbDVnuEKClh1HaPsJnZWtD87DmYcudhtdrbN3tu3buj5DAoD0EDGqKF1iIAsNPYOiNfKIUsLObJ+T0bVg-KZchitOyeByp4IS2QQmlQvtY-Wjj1yuMPJ4-hrtqwh7I1HmqXQDnOXXoheao1-LgWubEO5q1NLaUcADIe8wPymioGBTgNjBKdBEJUIyjAQX6AgmECJcL0QktqggLpMQuhQX8dKRwNouLGqoCIf56wlHIWCqLfylhznQXVZYdG0rHBAvBfwC+tGNmVSjyS124QnggNgckQO4FlWTUjtG+N6NsAh3As1P1zVL7gPpB4DgdC9AG2ZuIyNAbVkVtrY2wyxAKh4BiggOYYA+7SDYolfiRgqBQXCHC-NrFXaZDsGAJ1+gUnmERusewq9gq-sA+jWqK97C6O6F3YS3QhQeBAggFQrAHCtRdsaP+YTqAcA5ojVyv7-LrHmrxwTpjmmjPscbZxlt5mt2vK7ax75vyED8Ck+e8NcKzls-YYh3zHzrEpb6wy84xBn2RdfVioXPBFlBeMsAWZzzjKoD5yoESoKnuC-CMLwDmqJckcYB98DNWtDhuBbjy9YLo1IDEM9slQuX2bYl1Ln5GVgCCYx2qUFl7QUedWDDtwcOEfHv0iwrUvv0m4oAF6QzEKrlQ1ueC2-eToHtcb6L66G9C6rRu-ujqz+w0d0bxca4ZS+lQ5J1ekGIJLs7TuqCy6CzX1AEKUvMLV9rovC3E-gD16KGLJckBlykyw371jg-gvDaPgvNv28vdF2ARg9uNdV+l87uXDem-K9g63wvFfi+d7mhd8wvf20D-TzC4fJrrH5vDRf6dPOdDb+ILvpdUiqAL4r0vmvdf5cZVQCw5v7Ct8p8d8O8aUPkVAoAD8j9+8MBB9ftR9Cd4Dy0TV+c48X0hcGVwC39K9HcZdV8FdkCN8ldUDO91tOhkNsUJJYCjd5MxtqCx0y078QAVN+A1MNkNMq1tNdN9MKBDMDljMKdTMqcN0acytQC61PsR5UB7NHMg1nNzVYVgUIV80FClDo1dVQATkdMdBFlEd9IHtwtVg+8y57tHtDlVNxwUNmNdk9MGgKBVhVtCt-lXhiQMwLkX0HDS4nDoA5l+ALlmDWDLDSc+CsNBDcMLM+MiNdcyNRFOhVhAgmgMxdAqR70RE3BUByNEBAVO9Vh0JzAgVrFBVmFBVR0WETViixBSj+U1DdVODUV2VMjgAjCMATCDCdDA8WjDlLseAYAUodNTDVguj8QcBUA+jACtV-U9U9JOg7cGU-UdVOhiNWBgA2ikd9DDkmiOi485jdVNttiFirANBzAOhgBQ9GV+BI9UAxAADY9ZjtUdjbiJjFjMgu0PthMgV+UeU6stAxthBoNviHtoNqjpjNDnV6jOgXdUj9I4gQBoT7D6BHDMhUASQwBih0gd0SsAsNiY9rNhMAt8tWtG9hAABSHEprRlFxIUFEmQJAVYIYwkkkno-SPlEkjEhY13ETWACFWAZ5MQVYNofgUUIrITZfV-GgCFckRQfQUgEjIkFVMUVYcPLbRpS4rYu44EsQsXZnSRLzCNc1MbYFZhf4g04QJjXVDAzQUXXYtU5rRKLtLQc0n1FncFMbPPaFF0k1RjRgngUvK0iYmYzVPYm01gF4lY-SXlAwvvcDPlf4tzGMrzO9UvWotAMEroB0h4+YyYhojY8Mw5UMy49fAYvuA9RkkYlhMUgwwY9CUssU-031a0+PJZMAI4iAe0zVH09M+4gM+sg4ps4404iPKPUFLtNXd44ot0wtflZ0ichglZD5RlefDs9U+VOlRcoM54zvVsusiYzFKMtZMbEfYoj3FhKoxgjgWYxgWsrNes20zvZYgPJHbHEFcc2FfNMbF8oErImlLQ5MqY1Mrs7cgMu7FMxo4-Zoio1o+8sMv-Toosq7EsngE1csmCoSK7OkhCmsy01chsw4joTcq8gC31Bc-8jM7C3siAE42HAcy44FYcm494vU4Ff448s5N8j46NVcy88Ykim8jUvCri1lJ0-4s1FikdfPU8hlOaTiwMp40gEMyC9AbUnHccycxisbFSj8pMpE38viwMiSqgLSrM0C+7bEvM0FbEro+CzfZCmGHgNC2DKS7sxs5snS60vS30kins5siiv3KisNWi-rd43U1SurMo-4-lMo00zoDAxwTC4i3VGSu06Kx00-eFb42bUotK1hHzWcnQfipcwldy+Kni2lO83QhSoVJStK6PFig00FbnHKmNb0mKr80E7SpK1cgy8ErEgs0ygsiyjeHTUFJCwslC2yqswajC5-FcuK-Ypy3C9qmajgQq2anC8i-s84qPE1fymgHNGDb4t0g0i-Kqi-aNMUKkZaz84wb8zqy6gqrC4qj5FygizlVzPcsFDKk1d67K2lFbNRQSKkTSlMhyx4h6nQV4sk-tcFYFA6sFYok3OrGdC5C6wG384G7i4Mjc1cncoNV6tK9hPaz6-G+q2lTVDw1w0Qq61qzItGoqjGjU8GgLIYrTINNZVKwm9hOGzhE8hqjikEuo1G2Krc9G9c3ixczlVm50xQr4z6qrNQiAKgHwtwvmn86mwW-C4W2S281k5rSGp8tKuTa9GWmraNOHMUaUjKFG1Wqai6hKzGzVIEPIobKGg6y-V8qDVQxg4yZG5Wm6mmhY0GkABmhYpm13F6yFN6gomqyO6NYTE7NwYgqa6SsINwYAcw9TIzSIxARgaItwWI+nH5V4JnREwTPBUgOIhI-gJIlI3OtIjIzoVUkGpYvM5hYkwwoylukkxUhpVQS40kn8GPaIKk9tGSTk7ky3Pu4O9CFIoTQMV4JAAAQgFNW0bTaHgAnua3xP4BC2ZL5OlMFP+WFJr3pXFNAylJlJ2TFAbo8rmvIsrOGJb0OXZKkOgxYSQBNVkATtpTAGrgWS-x+SkxNyCpYShTSuAc9Iat0Dk1gDmyf2XJO1kDAFTpYIsNQAztbWIyzpzsyPLvYEruSOTv0jro4Dj3gbL01VIYwZlG8rDw2suOuPsPrwV2jzGNIcO2ROuya2QCDuayIQyDuyHs+jEBSzVFHp5JIeRIZSI0ZOAHiNwaroIdQa+XYDFHgHEYQckfQaPSwBkYrvkchMUdUB4HCCQDUbADTPIfYd12obOIuOYcOTwJ-wftMfPM2woasfWtsbC3scYccaEZuIsfUc1Tmlccsazusd8qVwYe-30quJYYkbbKgBCYQcob1w8c2oMIcZiaILYeSasbJq8JcN8J3TTrYLQYeRSawdiKfrVH5WEHMHYXMB3VOPhzKuDzRjRxRMDFW0UGwe1uuz4dQAEeiAHs4AK1mVeDcFpPyzYE8OLuKGE3pVBXJEaFkHomxQgHD0BA4BJWhTORoGAftP5UdG1sWeWeIFWdgHWc2c6B2aFXtIOZoCOdMZSc20SghJnqkNqfqcaeed11QD9AbT4rcazv+dIKWqAyWOqZfrfo-pybABSckaZwuXebdy5OsVkGgfXv6du0GeKGHoHtE1gHRegd+azsRfJtechfmZEzRYxYFwCfhd1wkvoBFNl3oB6YWIgAuTcHwGDFZXrRYLkAMFLk2QwF43CE-o+XgZgG4e+1+MNpH2EFfMVdvwatQEZLUc7VFxdTtSxWlesNxM6FVWiE4HVbjXSQWQME+ngCQG4exaYHFVZU1Ypo+RyZgA4eUHA2YTdOPNoJNV9ZnNpVQ12TJ1FxCJw24xENyxAEztI3KoHXPTNQhWhu+PHWhuLEkXAE5kYXQGEEuOEFmzkwkU8CAA).

**Comment by angrytongan** [comment]
Thanks for the fast fix. Looking forward to 1.0.0!

**Comment by vrimar** [comment]
Added to v0.2.3.
