### ISSUE TITLE
List with "false" item not triggering onSelect

### ISSUE THREAD

**Issue by chocolatkey** [vrimar/construct-ui#16]
I've reproduced the issue in a simplified form in [this flems](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgAHTSTJAIQCuxYvQpyFASXGb5kgMoxY1YgBkIE-QssTtjLHNaSAvJIDCAVW0BuOXKwUnAmMGYwACZukgAM-mhy4lIAggAOqdGyBgoAbhAwAO6IkgAUAJRuAHySWCUyIMgSAJ6wrqkYEREQaADmiADMMakAHgC69RQ1JcamFlbEk1kKy8vUULQhAPJoM2HExcQATsowNivLRxA9PTCHxbUqahrSWudvEEIASlckxbr0cHwHgAEgBRABqn02ADkAPoAEU2AHVoWc3isoBgAEYmYohWaRNHohRwZRYzE4qDFeq7cIRRD1V5vVhlIkrCCOODFZAxSYARkmACZJv1RmzlhyYFhPkwIrdiiVJVgKq5qrU7MQHFLFkziZIKbjJErxW98XtIsUlW5XO4zXTdSsWSbJPRaftSkqVdU7Ywou5jQ7lpAoIxDtjYMUwBgoCFnRgzBAcjBtGg5cM8aF7dlJCyys54lh8FhaMoGCUIrRqMocAx8FjaBEmpM0qkyr5KDRaFhUtBbngsdiTB2fRAAXgYogYgBaQUAdkQgoAHGwOCBMDg8PhqHABJ3hMweGwxSAoN0ANYIFCcDc8LAcwiHaAd5SHcg8EjEVJcgD039LqTPHoty7b872IB9oAAAUFfAYnwAAWUD70fKAi26fB+A7YgmlSbgQDgahH1SUR2GvPCkmOMwp2UCA0LQDDdxfN8QA-L9EF-f9AOArBvwo5QqJoyC4JgwVv1PLFeIBI5+OIajaLvejMKobDcLwAiiNEKgRzHHhBQAVgXPlFwANkFGcDMFIzZ0FFcyLwbo0y3Hdn1fPBWJ-P80AAoC6B4viBIgIT8BEsSIAkhyYGGJzdxUvDmlgI9WCAA)

The first item in the list, with the value `0` cannot be selected (once unselected) because it is "false". I've think I've narrowed down the issue to these lines:
https://github.com/vrimar/construct-ui/blob/master/src/components/query-list/index.ts#L396
https://github.com/vrimar/construct-ui/blob/master/src/components/query-list/index.ts#L451
where the selected item is first checked to be true. `0` is not true in JS, so the `onSelect` is never called.

If this is by design, then I can work around it by having all items' number values be +1, but if not, then I think this is a bug, because there are use cases where an item's value could be something that is considered "false".

**Comment by vrimar** [comment]
Fixed in v0.2.3.
