### ISSUE TITLE
Buttons using basic: true change background on hover

### ISSUE THREAD

**Issue by angrytongan** [vrimar/construct-ui#17]
When using `basic: true` on a `Button`, the background where the button would be if basic were false changes colour on hover. This makes it appear that there is a borderless button on hover, rather than no button at all.

Easiest to see on intent `negative` if you zoom in. Latest Chrome, Mac OS X.

```javascript
const {
    Button

} = CUI;

const ButtonIntent = {
    view: () => {
        const intents = [ 'primary', 'positive', 'negative', 'warning' ];

        return [
            intents.map((i) => m(Button, {
                basic: false,
                intent: i,
                iconLeft: 'settings',
            })),

            intents.map((i) => m(Button, {
                basic: true,
                intent: i,
                iconLeft: 'settings',
            })),
        ];
    },
};

document.addEventListener('DOMContentLoaded', () => {
    m.route(document.body, '/', {
        '/': ButtonIntent
    });
});
```

**Comment by vrimar** [comment]
Are you referring to the light background when hovering over a basic button? 

![Capture](https://user-images.githubusercontent.com/5660247/76808751-1364a980-67bf-11ea-9e21-d400c4e6a4d4.PNG)

**Comment by angrytongan** [comment]
Yep. By design?

**Comment by vrimar** [comment]
Yep, that's intentional.
