### ISSUE TITLE
compile error, has no default export

### ISSUE THREAD

**Issue by kyleada** [vrimar/construct-ui#19]
Hi, thank you for your work. I tries this library in existed project, but showed these errors. when I  add

> "allowSyntheticDefaultImports": true

it continued to report new errors.

../../ui/node_modules/construct-ui/lib/esm/_shared/attrs.d.ts(1,8): error TS1192: Module '"/Users/wangkai/perfetto/code/perfetto/ui/node_modules/@types/mithril/index"' has no default export.
../../ui/node_modules/construct-ui/lib/esm/_shared/utils.d.ts(1,8): error TS1192: Module '"/Users/wangkai/perfetto/code/perfetto/ui/node_modules/@types/mithril/index"' has no default export.
../../ui/node_modules/construct-ui/lib/esm/components/abstract-component/index.d.ts(1,8): error TS1192: Module '"/Users/wangkai/perfetto/code/perfetto/ui/node_modules/@types/mithril/index"' has no default export.

**Comment by vrimar** [comment]
Could you provide an example repo with the issue?
