### ISSUE TITLE
should cards have a fluid option?

### ISSUE THREAD

**Issue by fuzetsu** [vrimar/construct-ui#2]
Right now cards seem to have a set `max-width` of `320px`, easy enough to override with styles, but it might be nice to have a fluid option to remove that max-width.

Maybe I'm abusing cards, and should be making my own container.

**Comment by abidingotter** [comment]
I have done the same, so if you are abusing the cards, you are not alone :)

**Comment by vrimar** [comment]
I'll add a `fluid` attr, it'll keep it consistent with other components.

**Comment by vrimar** [comment]
Added in 0.1.10.
