### ISSUE TITLE
Drawer example code not working for onClose

### ISSUE THREAD

**Issue by jobqueue** [vrimar/construct-ui#21]
I tried example code here: [Example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgAHTSTJAIQCuxYvQpyFASXGb5kgMLKJtLAGUYsasX0KVa+gHEATrWUAHO5IAiLjADuMC7ePhAYULQA5t6W1sQAMhAS3kkS2oxY3gBitNQmALIYmFHBcqySALxGAKraANxycrn5cEUlwfhwhLQBLSYA8mhQAJ5DACoYAEYAFACUjWhysFLJYRHRAx5MVZJgEXAwiyuSa-5BLls71ftQh8cwUofxMAAmhrSRLoty4lIAgh4PLtZAYAG4QGABRCSeZVAB80i0CkkLkeyhc8iwMxkIGQEhGsEqHgwr1eEDQUUQAGYAAweAAeAF1cRRJMhkSjJNiHOo0K53F5pJI4BAAF4wGG4hlwXGSdjszlc7kzXkaJEGZUoiBCBIwMDEGG6ehwfCGf4JACiADkfP8AEreLUKKDTKxSkBXeTrSJRVlKrX0ahQHUAaxhcMqiJma3Cvq9u2ILmUMDmAZRrDm+nTCh5qj5bNBzu1uv1hskxrQpvMlvG4201qc5idztdU3dklxCb8gTKlBzKKDIeo4dhcwRsLOvcu23k1STKbTmuVmezy652LiMBsaVsGuLCggmTgMI5IEUUBTrM7IAAChiPLBr7j7W9nyBXDAmLimS2tUeYCwV80FeYIYQArAEQHDcZl3DJAMLaDlTbDsIL-A9nm3RhXnAzIqkqapMJsN4Pi+dDiyERgGHtCAohIGFsVxa8iwPLUCVgGEWNYrVCBgWj6JvABGekGX9dduIUAIIFeYhCA9YTGTEiStSmWgXFAlx7VJCATA9ABWESlOUrkpgwEcojcZQQNwwCkK1Vg7IzJcJNXJCINvNFyWoDBGAjABHFMXBGNkIPHKNHIg-B1ASXpgkMDBDnmfAKWDZRQLgGYAuCEYotoGKLnixK5izJD6C3GwbMgqNYSI7DSLU3ZQvIlEk1o0oXAY1V83VLiDx1eg9QNI1xHwHx7QGW8rXGZquRQqAPUMHpaEOSQ6C+IzWP6tAaLo8tK1NQwAAlLQANXG60AH0fAGAB1a0kMzAdXKWcTcxmYxTAsKwsMQ17Bw8YgIBNU9cQAKWKGB31B2hCCWSgb3BtBHh-GbJFA-ZlCgYgToiFMPURyH+z+hRWqidr-jUFwT33bitsGvaRpqGt7XMB6nuc5UmRKl6tWxH1ol+4tki9cC4H5qIvWa+hDEiQ4IzC6NYw2CXZ12W5Dm54tAeIDib3FjblUokQPXGeBAcpA2uTAWhaEYDrFWJlU1TQQXuLmhbZcJ1GFCHMN5YnGMxbjTZVZuA5UwejmtRZcTnvTPnzmCV3-zgEXTjFxOZyYZqjYYBb6Co4hLZRDxlqPIG0A9WADWLn20Bl5bJTHAOpwuBMw7uCPY6jyQucWBQHLQVgfjQLB8CwdwGBmV48mUHAGHwVTXmCyRAQ8BY5EoEBaorhAeFpRBaQAWgATgAJkPtgOBATAcDwfBqDgAQaALkQWFYX8QBDNBQz31Ab64HgLAR5CAuGgFvDE5AeAkGIB4E8AB6eBVkPChiiA-Mw8DgGyTAVAAAAoJfABCABsmCQE4PwPwLexARjbDwHAagYCAZX04HfHgfxkw2CPsoCA48KQUOfpAvAMC4GIEQcg1B6CsDwPYcoTh3DcG0kIYQ2k8CQxTGkSaBccieHALQPwqhNDuDbwYRAJh7AWFGIpKBBkD8n4QJcFAkAwiEFILQCgtBdApEyO0QopRwlVEQHUVYmANjH7P2obQng7FcBUB3iaPAB9j4H2ErSAA7OktgTJWBAA)

The only changes I made are changing the import statement to 
```
import './node_modules/construct-ui/lib/index.css'
import {
    Button,
    Icons,
    CustomSelect,
    ButtonGroup,
    Drawer,
    Dialog,
    SelectList,
    ListItem,
    FocusManager
  } from 'construct-ui';
```

The onClose() is reached in the drawer, but `isDrawerOpen = false;` is not closing the Drawer. Wondering if I missed something from Mithril.js to make this work. 
```
Version information
    "construct-ui": "^0.2.3",
    "mithril": "^2.0.4"
```

**Comment by vrimar** [comment]
The master branch targets Mithril@1.x while the 1.0 branch targets Mithril@2.x. Can you provide a reproducible example?
