### ISSUE TITLE
Callout applies a style that breaks icons inside its content

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#25]
The callout component applies an absolute position to `.cui-callout .cui-icon`, which breaks icons inside the callout content. Applying the style to `.cui-callout > .cui-icon` could be one way of preventing this:

![image](https://user-images.githubusercontent.com/1273926/78729455-f0757300-78ee-11ea-967a-793cf787f877.png)

**Comment by vrimar** [comment]
Fixed in v0.2.4.
