### ISSUE TITLE
construct-ui Grid is actually... flex?

### ISSUE THREAD

**Issue by angrytongan** [vrimar/construct-ui#29]
Construct-ui `Grid` actually creates CSS using `flex`:

![Screen Shot 2020-04-25 at 6 49 10 pm](https://user-images.githubusercontent.com/1642050/80275574-8f8acf00-8725-11ea-94a6-8fd6490ff6d4.png)

Uh, not sure what to say about this one...? Should it be called `Flex` instead? Or change `Grid` to use CSS `display: grid`? Leave as is?

Breaking change, here as a note. 1.0.0 branch.

**Comment by kczx3** [comment]
Why does it matter what it’s called? It’s just a name that creates abstraction over the implementation.

**Comment by vrimar** [comment]
As @kczx3 mentioned, it's just an abstraction similar to [bootstrap](https://getbootstrap.com/docs/4.0/layout/grid/), [semantic-ui](https://semantic-ui.com/collections/grid.html), [ant-design](https://ant.design/components/grid/) etc. which all use `display:flex`.
