### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#30]
Is there any recommended way to customize styles, e.g. override the primary intent colors?

**Comment by kczx3** [comment]
You should just need to override the color variables in a local sass file and import the entry point of construct’s sass files. You may need to import another file or two prior. 
[_variables.scss](https://github.com/vrimar/construct-ui/blob/master/src/_shared/_variables.scss)

**Comment by vrimar** [comment]
@kczx3 is right, the ideal way would be to override the variables, here's an [example](https://codesandbox.io/s/construct-ui-theme-example-ebsgv?file=/src/index.scss). If you're not using sass in your project it's a bit of a pain to introduce yet another dependency. I may look into a css-in-js solution in the future to allow a more versatile approach to themeing.

**Comment by raykyri** [comment]
That makes sense! Didn't see the !default flag there.

**Comment by frie** [comment]
There are a couple of "hard-coded" color stylings (`background:white;`) in the scss sources which do not make use of the color variables, so there currently is no way to change the coloring to a dark theme without touching the sources. At some places `background: $white;` is coded, which may be overriden by defining `$white` as black color...
See [.cui-list class](https://github.com/vrimar/construct-ui/blob/5a0d5b6bcd500c9b6beb1b6ea8791227013d58c5/src/components/list/index.scss#L24)
