### ISSUE TITLE
Hexagon icon is not available as Icons.HEXAGON

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#32]
It seems necessary to specify the icon as the string 'hexagon' instead.

**Comment by vrimar** [comment]
Are you using the latest version (v0.2.5)? Seems to be working fine in this [example](https://codesandbox.io/s/construct-ui-hexagon-5cbfp?file=/src/index.js).

**Comment by raykyri** [comment]
Must have been cached typings - restarting a few more times fixed it.
