### ISSUE TITLE
onSelect not being called on CustomSelect components

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#37]
The onSelect attribute on CustomSelect components doesn't seem to do anything.

Example (I am not 100% on this flems setup, but the issue occurs elsewhere too):

https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgAHTSTJAIQCuxYvQpyFASXGb5kgMLKJtLAGUYsasX0KVa+gHEATrWUAHO5IAiLjADuMC7ePhAYULQA5t6W1sQAMhAS3kkS2oxY3gBitNQmALIYmFHBcqySALxGAKraANxycrn5cEUlwfhwhLQBLSYA8mhQAJ5DACoYAEYAFACUjWhysFLJYRHRAx5MVZJgEXAwiyuSa-5BLls71ftQh8cwUofxMAAmhrSRLoty4lIAgh4PLtZAYAG4QGABRCSeZVAB80i0CkkLkeyhc8iwMxkIGQEhGsEqHgwr1eEDQUUQAGYAAweAAeAF1cRRJMhkSjJNiHOo0K53F5pJI4BAAF4wGG4hlwXGSdjszlc7kzYymCxWGA2Nmg5XK2geYgQehwGEckAAKWKMFZklxFtohCWlDtlutxFxTO8eoUrxg+2UUGIADUIspJa6rWgbZQlXriC4IFFSi5-moXKakQYfSiIEIEv7iDDdCb8DVzABRABK5jjyvYda59DiWqLsINRvocwRWZzXIiwWIMw7xrQC0bKNYE9YczrTLm3sk88WCinaFYPzQWHwWHcDBmrzyyhwDHwU1orxGbMBHnHaEoIGerdHCB4ACYAJyIN8AVjYHBATAcDwfBqDgAQaHoRhmB4NgvRAKAKQAa1fVBAK4PAsAgYhCETcgqAxcgeBIYgPFNAB6cjlDQDwkKiUCzHIrCcLwgABABGfBOIANiY7DcOgfB+AfYgRm2PA4GoRNDX-ThgJ4P4XGUGwAFplAgHcKSEiDCLwEiyMQSjqNo+i6CwcjFOU4g1IgVjaS4rjaXIxCpgsk0EysmzNLQbSRLE7hHykiAZPYOSAopP0GVA8CH104i1AMoyaLohjzMs1T1Lshz2KclzyIimAorAiDRPEngCVgB8nxsF88FpRBaRU+qctpAB2dq4NYIA

Btw, thanks for all your work on this library! I can try to send PRs upstream for some of these fixes if that would be helpful. So far everything has been minor or easy to patch around, and I have assumed you'd want to test any code that goes in.

**Comment by vrimar** [comment]
Fixed in v0.2.7. Looks like I have no tests for the CustomSelect component which I'll note down for the future.

PRs are most definitely welcome, I'm glad you've found the library useful!
