### ISSUE TITLE
m(Grid) crashes when passed `false` as a child element

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#39]
The check for how to render Col looks for `== null` but doesn't check for `false`. If passed false, Grid.prototype.renderCols will end up throwing an exception on the line `col.attrs = col.attrs || {};`

**Comment by vrimar** [comment]
Mithril version 1.x treats `false` and strings as a vnode while version 2.x does not. I've added a fix to check if the col passed in is an object. Fixed in version 0.2.8.
