### ISSUE TITLE
Consider dropping enquirejs 

### ISSUE THREAD

**Issue by panoply** [vrimar/construct-ui#41]
Grid depends upon enquirejs, maybe consider an alternative. I've had great success with [ssm](http://www.simplestatemanager.com/) for previous projects or rolling a simple stylesheet generated with [BSS](https://github.com/porsager/bss) could suffice too. The way in which Enquire pulls in and provides cjs support results in minor headaches when rolling with bundlers like Rollup.

Thanks for all the work on this vrimar, really is a beautiful addition to the mithril nexus. Would love to be able to buy you a coffee/beer/vodka. Thanks.

**Comment by vrimar** [comment]
I've replaced enquirejs with ssm in v0.2.9 and added the ability to [override the defaults](https://vrimar.github.io/construct-ui/#/utils/responsive-manager). I appreciate your interest in the library and thanks for the offer haha!

**Comment by vrimar** [comment]
I just realized I'm importing the minified version of ssm, `import ssm from 'simplestatemanager/dist/ssm.min.js';`.
Would this cause issues with rollup?

**Comment by panoply** [comment]
Will be no problems at all. Thanks a ton for the quick fix. I'll be leveraging construct UI heavily on an upcoming project, very excited to go deeper in the codebase.
