### ISSUE TITLE
Ajax Load in Select List

### ISSUE THREAD

**Issue by shekharsom** [vrimar/construct-ui#43]
This is a feature request.

In Select List, allow Ajax data to be pulled up  with a very long list. Initially only n items are pulled up but later as we scroll more, more data should be pulled up.

Also, during search, the data should be refreshed.

**Comment by vrimar** [comment]
Personally I think this should be a custom built component to prevent feature bloat. Here's a quick example I've spun up using construct-ui and mithril-infinite [example](https://codesandbox.io/s/construct-ui-mithril-infinite-ir0fd?file=/src/index.js).

**Comment by shekharsom** [comment]
Yes. That works great... Thanks. Though I still think it could be a feature of the  component. This is a regular requirement and not that easy to implement. Construct-UI is ultimately a collection of various components to make development faster and consistent. Just an opinion.

**Comment by panoply** [comment]
Personally, I'd vote against this. Construct is lean and does not get in the way. It ports over a lot of the same logic mithril developers embrace (ie: less is more) but more importantly the use cases where you need infinite scrolling features are minimal at best. When you're using a SPA framework like Mithril this type of feature is easy to apply and the whenever you would find yourself needing more complex functionality then mithril-infinite suffices.

**Comment by vrimar** [comment]
Closing as this is functionality beyond the scope of the component.
