### ISSUE TITLE
CustomSelect does not call onSelect

### ISSUE THREAD

**Issue by raykyri** [vrimar/construct-ui#44]
CustomSelect never invokes its callback when a selection item is clicked.

Example: https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgAHTSTJAIQCuxYvQpyFASXGb5kgMLKJtLAGUYsasX0KVa+gHEATrWUAHO5IAiLjADuMC7ePhAYULQA5t6W1sQAMhAS3kkS2oxY3gBitNQmALIYmFHBcqySALxGAKraANxycrn5cEUlwfhwhLQBLSYA8mhQAJ5DACoYAEYAFACUjWhysFLJYRHRAx5MVZJgEXAwiyuSa-5BLls71ftQh8cwUofxMAAmhrSRLoty4lIAgh4PLtZAYAG4QGABRCSeZVAB80i0CkkLkeyhc8iwMxkIGQEhGsEqHgwr1eEDQUUQAGYAAweAAeAF1cRRJMhkSjJNiHOo0K53F5pJI4BAAF4wGG4hlwXGSdjszlc7kzXkaJEGZUoiBCBIwMDEGG6ehwfCGf4JACiADkfP8AEreLUKKDTKxSkBXeTrSJRVlKrX0ahQHUAaxhcMqiJma3Cvq9u2ILmUMDmAZRrDm+nTCh5qj5bNBzu1uv1hskxrQpvMlvG4201qc5idztdU3dklxCb8gTKlBzKKDIeo4dhcwRsLOvcu23k1STKbTmuVmezy652LiMBsaVsGuLCggmTgMI5IEUUBTrM7IAAChiPLBr7j7W9nyBXDAmLimS2tUeYCwV80FeYIYQArAEQHDcZl3DJAMLaDlTbDsIL-A9nm3RhXnAzIqkqapMJsN4Pi+dDiyERgGHtCAohIGFsVxa8iwPLUCVgGEWNYrVCBgWj6JvABGekGX9dduIUAIIFeYhCA9YTGTEiStSmWgXFAlx7VJCATA9ABWESlOUrkpgwEcojcZQQNwwCkK1Vg7IzJcJNXJCINvNFyWoDBGAjABHFMXBGNkIPHKNHIg-B1ASXpgkMDBDnmfAKWDZRQLgGYAuCEYotoGKLnixK5izJD6C3GwbMgqNYSI7DSLU3ZQvIlEk1o0oXAY1V83VLiDx1eg9QNI1xHwHx7QGW8rXGZquRQqAPUMHpaEOSQ6C+IzWP6tAaLo8tK1NQwAAlLQANXG60AH0fAGAB1a0kMzAdXKWcTcxmYxTAsKwsMQ17Bw8YgIBNU9cQAKWKGB31B2hCCWSgb3BtBHh-GbJFA-ZlCgYgToiFMPURyH+z+hRWqidr-jUFwT33bitsGvaRpqGt7XMB7UbK76KthVMJ164sImCYgZgAcg5+I9ggTyAEJhecg92FKtAKQ8VQIx56q+edAWXCF0W0HKqRIGl2W2cV6hCGKUo1bCxFNa1bXdbFrCJeNuXiwqA8nrdlEmRKl6tWxH1ol+4tki9cC4CDqIvWa+hDEiQ4IxtydI7jTZZ12W5Dj94tAeIDibyjjblUokQPXGeBAcpYuuTAWhaEYDrFWJlU1TQEPuLmhaE8J1GFCHMMk4nGNU42aOM5uA5Uwe72uRZcTnvTQPzmCDv-zgcPTkjleZyYZrS4YBb6Co4ga5RDxlqPIG0A9WADTP-u0Hj5bJTHYepwuBNJ7uaeF+933FgKAcmgVgPw0BYHwFgdwDAZivDyMoHADB8CqVeMFSQgIPALDkJQEAtVr4IB4AANgAOyIEEgAJjYBwEAmAcB4HwNQOAAgaDHxECwVgv4QAhjQKGAhqAaFcDwFgI8hAXDQBwRicgPASDEA8CeAA9PIqyHhQxRAYWYeRwjZJiKgAAAUEvgAxhDNEiJ0fgfgODiAjG2HgOA1AxEAyoZwOhPA-jJhsAAWmUBASBFJzHMMkXgGRcjECKOUao9RWB5FuOUJ47xujaSGMMbSeRIYpjRJNAuOJPjhFoH8ZY6x3BcH2IgI49gziikUlAgyBhTCJEuCkSAYJCilFoBUWougUSYnZISUk4SqSIDpKqTAGpjDmFWJsTwdiuAqB4JNHgWkiBaQeMWcJWkxCNlsCZKwIAA

**Comment by vrimar** [comment]
The flems example in the README is not up to date with the latest library version. If you check [codesandbox](https://codesandbox.io/s/construct-ui-example-forked-5mg4y?file=/src/index.js) it works fine.

**Comment by vrimar** [comment]
If you're referring to the `oninput` and `onchange` events, the CustomSelect doesn't support those attrs although `onchange` probably should be. `onSelect` should also pass the event property as its second paramater.

**Comment by raykyri** [comment]
You're right! I was on an old library version too.
