### ISSUE TITLE
const assertion

### ISSUE THREAD

**Issue by panoply** [vrimar/construct-ui#68]
Hey @vrimar 

Hope all is well. 

It would be nice if const assertions were applied to the value maps.  We need not widen the literal types on these to obtain literal value, for example:

```ts
export const Classes = {
  XS: 'cui-xs',
  SM: 'cui-sm',
  LG: 'cui-lg',
  XL: 'cui-xl'
 // .... etc etc
} as const
```
I tend to reach for these exports rather frequently. Composing additional types from the maps is rather extraneous without assertion. A more elegant approach _could_ be exporting these as const enums because they are removed during compilation but this may result in some refactors across the codebase and in addition require exposure to raw `.ts` files in the distributed bundle.

**Comment by vrimar** [comment]
Yeah this makes sense, I'll be pushing an update for this in the next few days!
