### ISSUE TITLE
Tooltip not displayed on disabled Button

### ISSUE THREAD

**Issue by angrytongan** [vrimar/construct-ui#8]
`Tooltip` is not displayed when hovering over a disabled `Button`. Not sure if this is desired behaviour or not.

```
'use strict';

const {
    Button,
    FocusManager,
    Select,
    Tooltip,

} = CUI;
FocusManager.showFocusOnlyOnTab();

const DisabledButtonNoTooltip = () => {
    return {
        view: () => {
            return m('', [
                m(Tooltip, {
                    content: 'No tooltip on disabled button',
                    trigger: m(Button, {
                        label: 'A disabled button',
                        disabled: true,
                    }),
                }),
                m(Tooltip, {
                    content: 'Tooltip on disabled button',
                    trigger: m(Button, {
                        label: 'An enabled button',
                        disabled: false,
                    }),
                }),
            ]);
        },
    };
};
```

**Comment by vrimar** [comment]
Yeah, `disabled` elements in general don't trigger any DOM events. Setting `class="cui-disabled"` can be used as a work around as seen in this [example](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4hcYgAJgAHTSSFkgEIBXYsXoU5iyQDFa1FXACyGTAHMYAJy3zFAFVq0oxCAAdbOgMJQMcOPByrJIAvJJeAKoAkgDccnL6hiZmGJZW+HCEtADuiUYA8mhQAJ6F9hgARgAUAJRxaHLiUgAiEHCVsAAmqur0AHK0js6ubqGStaEAfNLailYwxCpW8rJ2OgoAbhAw2YjjNVMza+s684vLklhVAOTXFJLIsyfPl1VDLu73qy8-ikKMDD21wGkg0w3cknokk6bQ6ME6kgqag0aDuT1+z2IVgg5jSeyuPRRX3RGJ+1F8-iBhggAFoYe0Kl00cdSS9fBUYFAgQBBaGwxnwxHI+jM1nPVg1TxiyQSqViq7vEbElnS-4iIGKiFQ+lwhFI3qouXShRYnF416EzRHY1syqcnnyJi6oUG0U2k46gWdPZgDBQAJG42ykkY4Mqk4AXTqIYU7HRrHqCfiaCw+CwtBUDCqnQMKhwDHwFVonWK91aDK6lrQA01bhqlBAAVg1Fc9AQPAAjABmRAAJgAHGwOCBMDg8PhqP4G2rmDw2BGqFAIGgANbt1Ajrh4LAQYiEbHkKhLcg8EjENxwRAAeivmbcK-ME9oWCvO73B4AAh38N+AGyv3d92gfB+AbYhijcbhG2obE3FEdhODHHgmisFQWxpFQIDTZcQIEEBjzwM8L2vW80HvR86BfFC0OIDCIA-AAGH8fwYq8lwqK9qPQzDsLQXCwIgqC4Bg9x4OHUcoOXToYAADwnKcjysE8QCIy8bzvB8nyotssRoujGOYjtWPYq8pNk+S8PAyC8AkYpYHnVggA).

**Comment by angrytongan** [comment]
No worries. Thanks for the quick response!
